config/routes.rb
Rails.application.routes.draw do
  root "movies#index"
  get "bad_request" => "top#bad_request" # TODO:エラー発生用コマンド3行
  get "forbidden" => "top#forbidden"
  get "internal_server_error" => "top#internal_server_error"
  resources :movies, only: [:index, :show, :search] do
    get "search", on: :collection
    resources :performances do
        resources :seats do
          resources :reservations
        end
    end
  end
  resources :members do
    get "search", on: :collection
    resources :reservations
  end
  resource :session, only: [:create, :destroy]
  resource :account, only: [:show, :edit, :update, :destroy]
  resource :password, only:[:show, :edit, :update]
  # resources :performances
  resources :reservations # TODO:要らないかも？

  namespace :admin do
    root to: "top#index"
    resources :members do
      get "search", on: :collection
    end
    resources :movies do
      get "search", on: :collection
      resources :performances
    end
    resources :reservations, only: [:index]
  end
end

app/views/shared/_admin_menubar.html.erb
<nav class="menubar" id="admin-menubar">
  <ul>
    <%= menu_link_to "管理TOP", :admin_root %>
    <%= menu_link_to "映画管理", :admin_movies %>
    <%= menu_link_to "会員管理", :admin_members %>
    <%= menu_link_to "全予約管理", :admin_reservations %>
    <%= menu_link_to "TOP", :root %>
  </ul>
</nav>

app/views/shared/_errors.html.erb
<% if obj.errors.present? %>
    <div id="errors">
        <h3>エラーがあります。</h3>
        <ul>
            <%= obj.errors.full_messages.each do |msg| %>
                <li><%= msg %>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_header.html.erb
<h2><%= link_to "POPCORN", "/" %></h2>
<% if current_member %>
  <ul class="account-menu">
    <%= menu_link_to current_member.name + "さん", :account %>
    <%= menu_link_to "ログアウト", :session,
          method: :delete, data: { confirm: "ログアウトしますか？" } %>
    <% if current_member&.administrator? %>
    <% else %>
      <%= menu_link_to "予約内容確認", "/members/#{current_member.id}/reservations"%>
    <% end %>
  </ul>
<% end %>

<%# <nav class="menubar">
  <ul>
    <%= menu_link_to "TOP", "/" %>
    <%# <%= menu_link_to "会員名簿", :members %>
  <%# </ul>
</nav> %>

<%=
  if controller.kind_of?(Admin::Base)
    render "shared/admin_menubar"
  else
    render "shared/menubar"
  end
%>

app/views/shared/_login_form.html.erb
<h2>ログイン</h2>
<% if flash.alert %><p class="alert"><%= flash.alert %></p><% end %>
<%= form_tag :session, id: "login-form" do %>
  <div>
    <label>ユーザー名：</label>
    <input type="text" name ="name">
  </div>
  <div>
    <label>パスワード：</label>
    <input type="password" name="password">
  </div>
  <div>
    <input type="submit" value="ログイン">
  </div>
<% end %>
<div style="text-align:center; padding-bottom:20px;"><%= link_to "新規会員登録はこちら", new_member_path %></div>

app/views/shared/_member_form.html.erb
<%= render "shared/errors", obj: @member %>
<table class="attr">
    <tr>
        <th><%= form.label :name, "ユーザー名" %></th>
        <td><%= form.text_field :name %></td>
    </tr>
    <tr>
        <th><%= form.label :full_name, "氏名" %></th>
        <td><%= form.text_field :full_name %></td>
    </tr>
    <tr>
        <th>性別</th>
        <td>
        <%= form.radio_button :sex, 1 %>
        <%= form.label :sex_1, "男" %>
        <%= form.radio_button :sex, 2 %>
        <%= form.label :sex_2, "女" %>
        </td>
    </tr>
    <tr>
        <th><%= form.label :birthday, "誕生日",
                for: "member_birthday_1i" %></th>
        <td><%= form.date_select :birthday,
                start_year: 1940, end_year: Time.current.year,
                use_month_numbers: true %></td>
    </tr>
    <tr>
        <th><%= form.label :mail, "メールアドレス" %></th>
        <td><%= form.text_field :mail %></td>
    </tr>
    <tr>
        <th><%= form.label :credit_number, "クレジット番号" %></th>
        <td><%= form.text_field :credit_number %></td>
    </tr>
    <tr>
        <th><%= form.label :expiration_date, "有効期限" %></th>
        <td><%= form.date_select :expiration_date,
                start_year: Time.current.year, end_year: Time.current.year + 5,
                use_month_numbers: true, discard_day: true %></td>
    </tr>
    <tr>
        <th><%= form.label :authentication_number, "認証コード" %></th>
        <td><%= form.text_field :authentication_number %></td>
    </tr>
    <% if @member.new_record? %>
        <tr>
            <th><%= form.label :password, "パスワード"%></th>
            <td><%= form.text_field :password %></td>
        </tr>
    <% end %>
    <% if controller.kind_of?(Admin::MembersController) %>
    <tr>
      <th>管理者</th>
      <td>
        <%= form.check_box :administrator,
              disabled: !current_member.administrator? %>
        <%= form.label :administrator, "管理者" %>
      </td>
    </tr>
    <% end %>
</table>

app/views/shared/_menubar.html.erb
<nav class="menubar">
  <ul>
    <%= menu_link_to "TOP", :root %>
    <% if current_member %>
      <%= menu_link_to "会員名簿", :members %>
      <% if current_member.administrator? %>
        <%= menu_link_to "管理ページ", :admin_root %>
      <% end %>
    <% end %>
  </ul>
</nav>

app/views/shared/_movie_form.html.erb
<%= render "shared/errors", obj: @movie %>
<table class="attr">
    <tr>
        <th><%= form.label :title, "タイトル" %></th>
        <td><%= form.text_field :title %></td>
    </tr>
    <tr>
        <th><%= form.label :story, "ストーリー" %></th>
        <td><%= form.text_area :story %></td>
    </tr>
    <tr>
        <th><%= form.label :release_date, "公開日",
                for: "movie_release_date_1i" %></th>
        <td><%= form.date_select :release_date,
                start_year: Time.current.year, end_year: Time.current.year + 5,
                use_month_numbers: true %></td>
    </tr>
    <tr>
        <th><%= form.label :running_time, "上映時間" %></th>
        <td><%= form.text_field :running_time %>(分)</td>
    </tr>
    <tr>
        <th><%= form.label :distribution, "配給" %></th>
        <td><%= form.text_field :distribution %></td>
    </tr>
    <tr>
        <th><%= form.label :director, "監督" %></th>
        <td><%= form.text_field :director %></td>
    </tr>
    <tr>
        <th><%= form.label :actor, "出演" %></th>
        <td><%= form.text_field :actor %></td>
    </tr>
</table>

app/views/shared/_sidebar.html.erb
<%= render "shared/login_form" unless current_member %>

<h2>最新ニュース</h2>
<ul>
  <li><%= link_to "座席指定券の販売再開について", "#" %></li>
  <li><%= link_to "営業時間短縮等について", "#" %></li>
  <li><%= link_to "館内での食事について", "#" %></li>
  <li><%= link_to "新型コロナウイルス感染予防", "#" %></li>
  <li><%= link_to "新型コロナウイルスによる払い戻し及び有効期限延長について", "#" %></li>
  <li><%= link_to "劇場版「鬼滅の刃」無限列車編", "#" %></li>
  <li><%= link_to "「月曜のmoon」月曜のお話。", "#" %></li>
</ul>